import type { Metadata } from "next";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";
import { PageHero } from "@/components/common/PageHero";
import { Container } from "@/components/layout/Container";
import { Footer } from "@/components/layout/Footer";

const roles = [["Frontend Developers","React, Next.js, TypeScript, Tailwind CSS"],["Backend Developers","Node.js, APIs, data architecture, integrations"],["Mobile Developers","Native-quality Android and iOS experiences"],["UI/UX Designers","Research-led flows, interfaces, and design systems"]];
export const metadata: Metadata = { title: "Hire A Developer", description: "Add dedicated Atria Web Solutions talent to your product team." };
export default function HireADeveloperPage() { return <><PageHero eyebrow="Hire a developer" title={<>Extend your team with <span className="text-brand">proven talent.</span></>} description="Bring in focused design and engineering expertise when you need it—without compromising on quality or momentum." /><section className="bg-white py-24 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr]"><div><h2 className="text-3xl font-bold tracking-[-0.045em]">An extension of your in-house team.</h2><p className="mt-5 max-w-xl leading-7 text-muted">Our developers and designers work with your team&apos;s processes, tools, and priorities. Scale a product squad up for a critical release or add targeted expertise for a specific initiative.</p><div className="mt-10 grid gap-5 sm:grid-cols-2">{roles.map(([role,skills]) => <article className="rounded-2xl border border-line p-6 transition duration-300 hover:-translate-y-1 hover:shadow-card" key={role}><h3 className="font-bold">{role}</h3><p className="mt-3 text-sm leading-6 text-muted">{skills}</p></article>)}</div></div><aside className="rounded-3xl bg-[#1a0809] p-8 text-white sm:p-10"><p className="text-brand">How it works</p><ol className="mt-7 space-y-6">{["Tell us the skills and delivery goals you need.","Meet a carefully selected specialist from our team.","Start collaborating with a clear, flexible engagement."].map((item,index) => <li className="flex gap-4" key={item}><span className="grid size-7 shrink-0 place-items-center rounded-full bg-brand text-xs font-bold">0{index + 1}</span><span className="pt-1 text-sm leading-6 text-white/80">{item}</span></li>)}</ol><ul className="mt-10 space-y-3 border-t border-white/10 pt-8">{["Flexible engagement models", "Senior, vetted specialists", "Clear communication and accountability"].map((item) => <li className="flex gap-2 text-sm text-white/80" key={item}><CheckCircle2 className="text-brand" size={17} />{item}</li>)}</ul><Link href="/contact" className="mt-10 inline-flex min-h-11 items-center gap-2 rounded-lg bg-brand px-4 text-sm font-bold text-white transition-transform hover:scale-[1.02]">Build your team <ArrowRight size={16} /></Link></aside></div></Container></section><Footer /></>; }
